[2023-05-13 00:58:00,401] 	INFO 	22 	id_data.py 	<module>() 	ID Data Started
[2023-05-13 00:58:03,147] 	ERROR 	75 	id_data.py 	<module>() 	Error occurred during ID Data process. Error: {'code': 0, 'message': "we can't execute this request"}
